---
# tasks file for aws-snapshot-to-s3

- name: Create EC2 Instance
  local_action:
    module: ec2
    assign_public_ip: true
    ebs_optimized: true
    instance_tags: '{"key":"Name","key":"Snapshot-Exporter"}'
    instance_initiated_shutdown_behavior: "terminate"
    key_name: "{{ ec2_key_name }}"
    region: "{{ aws_region }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ami }}"
    wait: true
    count: 1
    vpc_subnet_id: "{{ subnet_id }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 15
        delete_on_termination: true
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  register: ec2_instance

- name: Create a volume from the snapshot and attach it to the instance
  local_action:
    module: ec2_vol
    instance: "{{ ec2_instance.instance_ids[0] }}"
    snapshot: "{{ snapshot_id }}"
    delete_on_termination: true
    device_name: "/dev/xvdf"
    name: "Snapshot-exporter-src"
    state: present
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  register: ec2_vol_src

- name: Create a volume to place the dd dump file
  local_action:
    module: ec2_vol
    instance: "{{ ec2_instance.instance_ids[0] }}"
    volume_size: "{{ ec2_vol_src.size }}"   # verify this variable name
    delete_on_termination: true
    device_name: "/dev/xvdg"
    name: "Snapshot-exporter-dst"
    state: present
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  register: ec2_vol_dst

- name: Initialize device and create partition
  parted:
    device: "/dev/xvdg"
    label: gpt
    number: 1
    state: present

- name: Create an xfs filesystem on /dev/xvdg1
  filesystem:
    fstype: xfs
    dev: /dev/xvdg1

- name: Mount export volume
  mount:
    path: /mnt/export
    src: /dev/xvdg1
    fstype: xfs
    opts: rw,noauto
    state: present

- name: Export the contents of the source volume to the temp volume with dd
  command:
    cmd: dd conv=fsync if=/dev/xvda of=/mnt/export/xvda.raw

- name: Copy export to S3
  aws_s3:
    bucket: "{{ s3_bucket }}"
    object: /xvda.raw
    src: /mnt/export/xvda.raw
    mode: put
    region: "{{ aws_region }}"
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"

- name: Shutdown the EC2 Instance
  local_action:
    module: ec2
    state: 'absent'
    instance_id: "ec2_instance.instance_ids[0]"

# - name: Delete the temp storage volume

# - name: Delete the temp volume that is from the source snapshot

# - name: Terminate the EC2 instance
